version: "3.5"

services:
  research:
    build:
      context: research
      args:
        JUPYTER_EXTERNAL_PORT: ${JUPYTER_EXTERNAL_PORT}
    volumes:
      - ./research:/mnt/code
      - ${DATA_VOLUME}:/mnt/data
    environment:
      TIMEZONE: America/Sao_Paulo
      SPARK_PUBLIC_DNS: ${SPARK_PUBLIC_DNS}
      SPARK_MASTER_PORT: ${SPARK_MASTER_PORT}
      SPARK_WORKER_WEBUI_PORT: ${SPARK_WORKER_PORT}
    ports:
      - ${SPARK_WORKER_PORT}:8081
      - ${SPARK_APPLICATION_PORT}:4040
      - ${JUPYTER_EXTERNAL_PORT}:${JUPYTER_EXTERNAL_PORT}
      - ${SPARK_MASTER_WEBUI_PORT}:8080
      - ${SPARK_MASTER_PORT}:7077
    image: portfolio-research
    container_name: portfolio-research-${CONTAINER_TAG}
    
#  nominatim:
#        container_name: nominatim
#        image: mediagis/nominatim:4.1
#        restart: always
#        ports:
#            - "8085:8085"
#        environment:
#            # see https://github.com/mediagis/nominatim-docker/tree/master/4.1#configuration for more options
#            # escolhida apenas banco do sudeste do brasil
#            PBF_URL: https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf
#            REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
#            NOMINATIM_PASSWORD: very_secure_password
#        volumes:
#            - nominatim-data:/var/lib/postgresql/14/main
#        shm_size: 1gb
        
#volumes:
#    nominatim-data:
